name: CI
on: [push, pull_request]

jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
        dc:
          - dmd-2.100.2
          - ldc-1.30.0

        python-version:
          - 3.9

    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/checkout@v3

      - name: Install clang
        uses: KyleMayes/install-llvm-action@v1.5.5
        with:
          version: "10.0"

      - name: Install D compiler
        # must go before setting LD_LIBRARY_PATH below
        uses: dlang-community/setup-dlang@v1.1.1
        with:
          compiler: ${{ matrix.dc }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Environment variables
        # This is so we can find libclang at runtime
        # We append to the current value in order to keep what's set by the D installation
        run: echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${{ env.LLVM_PATH }}/lib" >> $GITHUB_ENV

      - name: Run tests
        shell: bash
        run: make
        env:
          LIBRARY_PATH: ${{ env.LLVM_PATH }}/lib  # find libclang while linking

      - uses: codecov/codecov-action@v3
